@ECHO OFF
ECHO XALLOC DATA NOT VALID!!!! OK!!!! NOT USED HERE!!!!!! BECAUSE OF LARGE FILES, NEEDS TO BE DEBUNKED WHAT IT IS, ....SO CHECK THE MEMORY.LOG FILE AND THE PROCESS EXPLORER(?) FOR MEMORY USAGE WHEN RUNNING CONTINOUSLY.........THE FUNCTION CALLED MUS BE BUILD INTO THE TORURE/TEST LOOP. THEN THE ACTUAL MEMORY USAGE IS SHOW......
TIMEOUT 10
MCA-NBT-EDIT_NO_MEMORY_LEAK_NO_XALLOC.EXE DUMMY_VAR
pause