@ECHO OFF

REM CREATE LARGE REGION DIR WITH LOTS OF REGION FILES.
REM ALL WILL BE PUSHED FROM WORLD/REGION/R.*.*.MCA INTO WORLD/NBT/WORLD.GZIP.NBT
REM THEN ALL REGION FILES WILL BE EXTRACTED FROM THE WORLD/NBT/WORLD.GZIP.NBT FILE TO WORLD/NBT/R.*.*.MCA FILES.
REM READING A LARGER .NBT FILES TAKES VERY LONG COMPARED TO READ SEVERAL SMALL ONES, LIKE R.*.*.GZIP.NBT FILES, AND EVEN FASTER IS READING 1024 SEPERATE WORLD/NBT/R.*.*/*.GZIP.NBT FILES INTO .MCA (OTHER TEST.BAT)

MCA-NBT-EDIT.EXE world2nbt world
timeout 5

MCA-NBT-EDIT.EXE nbt2world world/nbt/world.gzip.nbt
timeout 5
